"""empty message

Revision ID: f887e7c2dbab
Revises: d95b907c0503
Create Date: 2025-07-16 15:58:29.010264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f887e7c2dbab'
down_revision = 'd95b907c0503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Post')
    # ### end Alembic commands ###
